### ISSUE TITLE
How to parse multiple args?

### ISSUE THREAD

**Issue by snowcrumble** [fd0/machma#10]
For example: 
`echo "a.jpg b.jpg" | machma -- cp $1 $2`

**Comment by fd0** [comment]
There's no way to do that from within, `machma`. It is meant to be a simple program. You could probably do that with a bit of shell magic, although I suspect that this won't handle corner cases.

**Comment by snowcrumble** [comment]
Thx for reply, I can do this by:
`echo "cp a.jpg b.jpg" | machma -- bash -c {}`
