### ISSUE TITLE
{} is replaced only when separated by spaces

### ISSUE THREAD

**Issue by johnny2k** [fd0/machma#2]
Here's an example of how I would like to use `machma` to replace parallel in my environment.

find . -name "*.png" | machma -- convert {} {}.jpg

Another way I've been experimenting with quotes and slashes to see if I get it to be interpreted correctly is by feeding it to `echo`.
find . -name "*.png" | machma -- echo {} {}.jpg

The expected result is that the original file would remain in place and a new one with the ".jpg" extension would be created.

What I get is a single file named "{}.jpg".

**Comment by fd0** [comment]
Your description is correct, at the moment `{}` will only be replaced as a whole.

**Comment by johnny2k** [comment]
Thanks! Works great now!

Do you have a preferred place to receive feature requests/feedback?

**Comment by fd0** [comment]
Just create an issue I suppose, there's no mailing list or so in place. Or write me an email :)
