### ISSUE TITLE
Status area "jumpy"

### ISSUE THREAD

**Issue by johnny2k** [fd0/machma#3]

**Comment by fd0** [comment]
Can you elaborate a bit?

**Comment by johnny2k** [comment]
Sorry, you can close this. I don't know how I accidentally submitted this before adding the description.

https://github.com/fd0/machma/issues/4

**Comment by fd0** [comment]
Okay, you could've also just edited the description ;)

**Comment by johnny2k** [comment]
I didn't realize it existed until after I saved the other one.
