### ISSUE TITLE
Status area "jumpy"

### ISSUE THREAD

**Issue by johnny2k** [fd0/machma#4]
The number of lines in the status area is variable so reading and keeping track of the processed/failed/workers area is difficult.

An example to see what I'm talking about is to run ` find / | machma -p 9 -- ls -alh {}` and try to keep an eye on the "processed" count.

Maybe there's a better solution but what I was thinking: adding empty lines so that the status area stays in the same location. So there would always be number of lines equal to the maximum workers count plus one.

**Comment by fd0** [comment]
Indeed, good point.

**Comment by fd0** [comment]
Could you try again? You can close this issue if that's better.

**Comment by fd0** [comment]
I'm going to close this as resolved.
